# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-16 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zinnia_customized', '0001_initial'),
        ('zinnia', '0004_on_delete_arg'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='country_flag',
            field=models.ManyToManyField(blank=True, related_name='blog_entry_country_flag', to='zinnia_customized.CountryFlag'),
        ),
    ]
