# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-16 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('abbreviation', models.CharField(max_length=4)),
                ('lang_code', models.CharField(blank=True, choices=[('', '---'), ('en', 'en'), ('en-us', 'en-us')], default='', max_length=20)),
            ],
        ),
    ]
